DELETE from allergen;
CALL allergen_add("Shellfish");
CALL allergen_add("Eggs");
CALL allergen_add("Fish");
CALL allergen_add("Milk");
CALL allergen_add("Peanuts");
CALL allergen_add("Soy");
CALL allergen_add("Nuts");
CALL allergen_add("Wheat");
CALL allergen_add("Gluten");
CALL allergen_add("Buckwheat");
CALL allergen_add("Lupin");
CALL allergen_add("Seafood");
CALL allergen_add("Mustard");
CALL allergen_add("Sesame");
CALL allergen_add("Sulfites");
CALL allergen_add("Propolis");
CALL allergen_add("Royal Jelly");
CALL allergen_add("Mango");
CALL allergen_add("Peach");
CALL allergen_add("Pork");
CALL allergen_add("Tomato");
CALL allergen_add("Natural Rubber Latex");
